package com.challenge.RestfulAPI.api.v1.models;

import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.time.LocalDate;

/**
 * @Author abdessamadM on 23/06/2020
 */

@Data
@NoArgsConstructor
@AllArgsConstructor
public class CommentDTO implements Serializable {

    @ApiModelProperty(notes = "Comment id automatically generated by database", example = "1")
    private Long id;

    @Size(max = 1000)
    @NotBlank
    @NotNull
    @ApiModelProperty(notes = "The comment of the movie", example = "Wonderful movie")
    private String comment;

    @NotBlank
    @ApiModelProperty(notes = "The date of the comment", example = "2020-06-23")
    private LocalDate date;

    @NotNull
    @ApiModelProperty(notes = "The movie commented")
    private MovieDTO movie;
}
